sudo: required
dist: trusty

language: haxe

os:
  - linux

haxe:
  - stable

install:
  - haxelib install hxcpp
  - haxelib install format
  - haxelib install mcli
  - haxelib install Sure
  - haxelib list

script:
  - haxe GeometrizeHaxeExample.hxml

  # Check the bin directory, run built executable as a sanity check
  - cd bin
  - ls -a
  - cd ..
  - cp bin/Main sample_images/Main
  - cd sample_images
  - chmod +x Main
  - ./Main -i "grapefruit.png" -o "output.png" -t rectangle -s 100 -c 500 -m 100 -a 170
  - ./Main -i "grapefruit.png" -o "output.svg" -t triangle -s 300 -c 100 -m 200 -a 255
  - ./Main -i "grapefruit.png" -o "output.json" -t ellipse -s 200 -c 250 -m 50 -a 128
  - ./Main -i "grapefruit.png" -o "output2.svg" -t quadratic_beziers -s 2500 -c 200 -m 50 -a 128